version: "3.5"

services:
  api01: &api
    build: 
      context: D:\Desktop\TI\projetos\rinha-de-backend
      dockerfile: Dockerfile
    hostname: api01
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=rustwarpcrud
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"
